baseURL = 'https://wileywimberly.github.io/hello/'
languageCode = 'en-us'
title = 'Hello'
theme = 'hello'

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[markup.goldmark.renderHooks.image]
enableDefault = true

[markup.goldmark.renderHooks.link]
enableDefault = true

[taxonomies]
    tag = "tags"
