baseURL = 'https://wileywimberly.github.io/hello/'
languageCode = 'en-us'
title = 'Hello World'
theme = 'hello'

[params]
background_color_class = "bg-dark-gray"

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[markup.goldmark.renderHooks.image]
enableDefault = true

[markup.goldmark.renderHooks.link]
enableDefault = true