baseURL = 'https://wileywimberly.github.io/hello/'
languageCode = 'en-us'
title = 'Hello World'
theme = 'ananke'

[params]
background_color_class = "bg-dark-gray"

[caches]
  [caches.images]
    dir = ':cacheDir/images'
